[tools]
node = "25.3.0"
rust = "1.92.0"
bun = "1.3.6"

# npm
"npm:lefthook" = "2.0.15"
"npm:@biomejs/biome" = "2.3.11"
"npm:cssmodules-language-server" = "1.5.2"
"npm:vscode-css-languageservice" = "6.3.9"
"npm:@astrojs/language-server" = "2.16.3"
"npm:@vtsls/language-server" = "0.3.0"
"npm:@olrtg/emmet-language-server" = "2.8.0"
"npm:fish-lsp" = "1.1.3"
"npm:pyright" = "1.1.408"
"npm:@tailwindcss/language-server" = "0.14.29"
"npm:eas-cli" = "16.28.0"
"npm:@shopify/cli" = "3.88.1"

# cargo
"cargo:stylua" = "2.3.1"
"cargo:protols" = "0.13.1"
"cargo:tinty" = "0.30.0"

# go
"go:github.com/sqls-server/sqls" = "0.2.28"
"go:github.com/caddyserver/caddy/v2/cmd/caddy" = "2.10.2"

# aqua
"aqua:LuaLS/lua-language-server" = "3.16.0"

[settings]
always_keep_download = false        # deleted after install by default
always_keep_install = false         # deleted on failure by default

trusted_config_paths = [
  '~/Code/Mine',
  '~/Code/My',
]

verbose = false
http_timeout = "30s"
jobs = 8
raw = true
yes = false

not_found_auto_install = true
task_output = "interleave"
paranoid = false

experimental = true

status = { missing_tools = "if_other_versions_installed", show_env = false, show_tools = false }
